version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root-Verzeichnis deines Angular-Projekts
    schedule:
      interval: "weekly" # Alternativ: "daily", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.x"] # Optional: Ignoriere bestimmte Versionsupdates
